# Generated by Django 2.0.4 on 2018-07-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
