# Generated by Django 2.0.4 on 2018-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0004_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='deck',
            field=models.ManyToManyField(to='coup.Card'),
        ),
    ]
