# Generated by Django 2.0.4 on 2018-07-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0005_auto_20180707_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='card',
            field=models.ForeignKey(null=True, on_delete=None, related_name='cards', to='coup.Card'),
        ),
    ]
