# Generated by Django 2.0.4 on 2018-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0008_auto_20180707_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ManyToManyField(to='coup.Card'),
        ),
    ]
