# Generated by Django 2.0.4 on 2018-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0009_player_hand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='card',
        ),
        migrations.AddField(
            model_name='deck',
            name='card',
            field=models.ManyToManyField(to='coup.Card'),
        ),
    ]
