# Generated by Django 2.0.4 on 2018-07-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0010_auto_20180708_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='card',
            new_name='cards',
        ),
    ]
