# Generated by Django 2.0.4 on 2018-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0011_auto_20180708_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deckNumber',
            field=models.IntegerField(default=0),
        ),
    ]
