# Generated by Django 2.0.4 on 2018-07-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0012_deck_decknumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_OF_CARDS', models.IntegerField(default=2)),
            ],
        ),
    ]
