# Generated by Django 2.0.4 on 2018-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0013_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='decks',
            field=models.ManyToManyField(to='coup.Deck'),
        ),
    ]
