# Generated by Django 2.0.4 on 2018-07-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0014_game_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='coup.Player'),
        ),
    ]
