# Generated by Django 2.0.4 on 2018-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0015_game_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ForeignKey(null=True, on_delete=None, to='coup.Card'),
        ),
    ]
