# Generated by Django 2.0.4 on 2018-07-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0016_auto_20180709_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
    ]
