# Generated by Django 2.0.4 on 2018-07-10 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0017_remove_deck_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular card across whole game', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('U', 'Up'), ('D', 'Down')], default='D', help_text='Card status', max_length=1)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coup.Card')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coup.Player')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='coup.Card'),
        ),
    ]
