# Generated by Django 2.0.4 on 2018-07-10 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0019_auto_20180710_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular card across whole game', primary_key=True, serialize=False),
        ),
    ]
