# Generated by Django 2.0.4 on 2018-07-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0021_auto_20180710_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='coup.CardInstance'),
        ),
    ]
