# Generated by Django 2.0.4 on 2018-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0022_auto_20180710_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardinstance',
            old_name='player',
            new_name='playername',
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.ManyToManyField(to='coup.CardInstance'),
        ),
    ]
