# Generated by Django 2.0.4 on 2018-07-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0023_auto_20180710_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
    ]
