# Generated by Django 2.0.4 on 2018-07-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0024_remove_card_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deckNumber',
        ),
    ]
