# Generated by Django 2.0.4 on 2018-07-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0025_remove_deck_decknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='decks',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
    ]
