# Generated by Django 2.0.4 on 2018-07-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0026_auto_20180710_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinstance',
            name='playername',
        ),
    ]
