# Generated by Django 2.0.4 on 2018-07-11 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0027_remove_cardinstance_playername'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinstance',
            name='playername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coup.Player'),
        ),
    ]
