# Generated by Django 2.0.4 on 2018-07-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0028_cardinstance_playername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinstance',
            name='playername',
        ),
    ]
