# Generated by Django 2.0.4 on 2018-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0031_auto_20180711_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ForeignKey(null=True, on_delete=None, to='coup.CardInstance'),
        ),
    ]
