# Generated by Django 2.0.4 on 2018-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0033_auto_20180712_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='shuffle_order',
            field=models.IntegerField(null=True),
        ),
    ]
