# Generated by Django 2.0.4 on 2018-07-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0034_deck_shuffle_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='shuffle_order',
        ),
        migrations.AddField(
            model_name='cardinstance',
            name='shuffle_order',
            field=models.IntegerField(null=True),
        ),
    ]
