# Generated by Django 2.0.4 on 2018-07-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0035_auto_20180716_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinstance',
            name='card',
        ),
        migrations.AddField(
            model_name='cardinstance',
            name='card',
            field=models.ManyToManyField(to='coup.Card'),
        ),
    ]
