# Generated by Django 2.0.4 on 2018-07-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0036_auto_20180717_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinstance',
            name='card',
        ),
        migrations.AddField(
            model_name='cardinstance',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coup.Card'),
        ),
    ]
