# Generated by Django 2.0.4 on 2018-07-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0037_auto_20180717_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='whoseTurn',
            field=models.IntegerField(default=0),
        ),
    ]
