# Generated by Django 2.0.4 on 2018-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coup', '0038_game_whoseturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerNumber',
            field=models.IntegerField(default=0),
        ),
    ]
